-- Six new comprehension passages, 30 questions. Every question was judged
-- by three independent hostile reviewers (a test-taker's advocate arguing for
-- wrong answers, a non-native-fairness reviewer, a psychometrician), with
-- flagged items repaired and re-judged; the batch was then re-reviewed by hand
-- before this insert. This bank replaces a single passage that was hardcoded
-- in the client bundle and served to everyone forever. One passage is dealt
-- per attempt, so a leaked key now covers 1/7 of comprehension, not all of it.
do $$
declare v_p uuid;
begin
  insert into public.english_test_passages (passage_text) values ('Subject: Moving our weekly call

Hi Morgan,

Starting next month, our team meets with the auditors every Tuesday morning, so I can no longer make our usual 9:00 a.m. call. Could we shift it to Thursdays at 2:00 p.m. instead? Before you confirm, please check the shared calendar — I noticed two client bookings are already in that slot for the first two Thursdays. If those can''t be moved, offer me another afternoon and I''ll work around it. Once we settle on a time, please update the recurring invite through the end of the year.

Thanks,
Alex') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is the main purpose of Alex''s email?', '["To ask Morgan to prepare for an audit", "To propose a new time for a regular call", "To introduce a new member of the team", "To cancel all calls for the rest of the year"]'::jsonb, 1, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'According to the email, what does Alex say about the first two Thursday afternoons?', '["Alex has meetings with the auditors at that time", "The calendar shows that those afternoons are free", "The recurring invite has already been moved to those dates", "Appointments with clients are already scheduled at that time"]'::jsonb, 3, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why can Alex no longer join the usual 9:00 a.m. call?', '["Alex''s team has a new regular meeting with the auditors", "Morgan asked to move the call to a later time", "Two clients have booked calls with Alex at 9:00 a.m.", "The shared calendar no longer shows the usual call"]'::jsonb, 0, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'After Alex and Morgan agree on a new time, what will Morgan most likely do?', '["Send the auditors an invitation to the weekly call", "Book a meeting room for the new call time", "Change the repeating calendar invitation to the agreed time", "Cancel the recurring invite for the rest of the year"]'::jsonb, 2, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In the email, what does Alex mean by ''I''ll work around it''?', '["Alex will keep working while the call takes place", "Alex will adjust their schedule to fit the offered time", "Alex will cancel the call to avoid the scheduling conflict", "Alex will ask the auditors to change their meeting time"]'::jsonb, 1, 5, true, v_p);
  insert into public.english_test_passages (passage_text) values ('Quick update on invoice #2148 for Harborview Consulting. The amount we sent yesterday was wrong: it showed $4,850 instead of $3,850, because a canceled design task was never removed from the billing sheet. I have already spoken with the client''s finance contact, and she has agreed to disregard the original document. Accounts will issue a corrected invoice this afternoon, and I will forward it to the client once Alex signs off. Until then, please do not record any payment against this invoice in our system. Apologies for the extra steps. — Sam') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is the main purpose of Sam''s message?', '["To ask Alex to cancel a design task for Harborview", "To explain an invoice error and how it is being corrected", "To request immediate payment of invoice #2148", "To introduce a new finance contact to the team"]'::jsonb, 1, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'According to the message, what amount should the invoice have shown?', '["$4,850", "$4,150", "$3,850", "$3,580"]'::jsonb, 2, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why was the amount on the original invoice wrong?', '["A canceled task was still included on the billing sheet", "The client''s finance contact had requested a higher amount", "Accounts sent the invoice to the wrong company", "Alex approved the invoice before it was ready"]'::jsonb, 0, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What does the message suggest will happen once the corrected invoice has been sent to the client?', '["The team will be able to record the client''s payment in the system", "The client will be expected to pay the original $4,850 amount", "The canceled design task will be added back to the billing sheet", "The finance contact will be asked to ignore the corrected invoice"]'::jsonb, 0, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In this message, the phrase "once Alex signs off" is closest in meaning to:', '["once Alex gives his approval", "once Alex logs out of the system", "once Alex adds a closing line to the email", "once Alex finishes work for the day"]'::jsonb, 0, 5, true, v_p);
  insert into public.english_test_passages (passage_text) values ('Subject: Client meeting prep — new deadline

Hi Dana,

Quick update. The client has moved our review meeting from Friday to Wednesday morning, so I need the summary document earlier than we planned. Could you pull together the key points from the March and April reports — decisions made, open questions, and next steps — into a single two-page summary? Please send me a draft by Tuesday at noon so I have time to look it over before the meeting. If any figures are missing from the reports, flag them rather than leaving blanks. Thanks for turning this around quickly.

Best,
Morgan') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is the main purpose of this email?', '["To announce the results of the client meeting", "To request changes to the March and April reports", "To ask for a summary document by an earlier deadline", "To invite Dana to lead Wednesday''s meeting"]'::jsonb, 2, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'According to the email, when should Dana send Morgan the draft?', '["By Friday morning", "By Tuesday at noon", "By Wednesday morning", "By the end of the month"]'::jsonb, 1, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why does Morgan need the summary document earlier than planned?', '["Dana asked for extra time to prepare it", "The client''s figures arrived later than expected", "Morgan will be out of the office on Friday", "The client moved the meeting to an earlier day"]'::jsonb, 3, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What will Morgan most likely do after receiving the draft?', '["Read through it before the Wednesday meeting", "Forward it to the client without changes", "Ask the client to return to the Friday date", "Add the missing figures to the March report"]'::jsonb, 0, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In this email, the phrase "turning this around quickly" is closest in meaning to:', '["sending the reports back to the client", "finishing the task in a short time", "changing the direction of the project", "rescheduling the meeting at short notice"]'::jsonb, 1, 5, true, v_p);
  insert into public.english_test_passages (passage_text) values ('Hi Jordan — quick update on the director''s trip next week. The flight to the conference is booked, and I have paid for the return ticket as well. The airport transfer is arranged for both days. The only thing still open is the hotel: they emailed to say our preferred room type is sold out, so they are checking whether a similar room is available at the same rate. They promised an answer by tomorrow morning. If they cannot confirm by then, I will book the backup hotel across the street instead. Could you hold off on sending the final itinerary until the hotel is settled?') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is the main purpose of this message?', '["To ask a colleague to look for a cheaper flight", "To report the progress of the travel preparations", "To complain about the organization of the conference", "To request more money for the director''s hotel stay"]'::jsonb, 1, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Which of these tasks does the writer say is already finished?', '["Reserving the hotel room for the trip", "Sending out the final itinerary", "Setting up transport to and from the airport", "Booking a room at the backup hotel"]'::jsonb, 2, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why is the hotel booking still unconfirmed?', '["The writer has not yet contacted the hotel", "The hotel stopped answering messages", "The room''s price rose above the agreed budget", "The room they wanted is fully booked"]'::jsonb, 3, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Based on the message, what will Jordan most likely do next?', '["Wait for the hotel decision before sharing the travel plan", "Send out the final itinerary right away", "Cancel the director''s registration for the conference", "Contact the airline to change the return flight"]'::jsonb, 0, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In the message, what does "hold off on sending" mean?', '["Send it only to the director", "Delay sending it for now", "Send a shorter version of it", "Send it as soon as possible"]'::jsonb, 1, 5, true, v_p);
  insert into public.english_test_passages (passage_text) values ('Subject: Daniel''s first week — remaining setup

Hi Alex,

Daniel joins the team on Monday, and most of his setup is finished. His email account and calendar are active, and he has signed the employment contract. Two things are still open: he cannot access the shared drive yet, and we have not received his signed confidentiality agreement. The drive access is waiting on IT because our request was sent to the old support address. Could you resend it to the new one today? Once both items are done, I will add Daniel to the client folders so he can start real work.

Thanks,
Mira') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is the main purpose of Mira''s email?', '["To report that a new employee''s setup has been completely finished", "To ask Alex to help finish the last parts of a new employee''s setup", "To introduce Daniel to the team''s most important clients", "To announce that Daniel''s start date has been delayed"]'::jsonb, 1, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'According to the email, which part of Daniel''s setup is already finished?', '["His access to the shared drive", "His signed confidentiality agreement", "His email account and calendar", "His access to the client folders"]'::jsonb, 2, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why does Daniel not have access to the shared drive yet?', '["He has not yet signed his employment contract", "No access request has been sent to IT yet", "The access request went to an outdated IT contact", "The team has not received his signed confidentiality agreement"]'::jsonb, 2, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What will most likely happen once both of the open items are taken care of?', '["Mira will ask Daniel to sign his employment contract", "Daniel will get access to the folders used for client work", "IT will set up Daniel''s email and calendar accounts", "Mira will send IT a reminder about the drive access request"]'::jsonb, 1, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In the email, Mira writes that two things are "still open". What does "still open" mean here?', '["Available for anyone to use", "Unlocked during working hours", "Able to be discussed again", "Not yet finished or resolved"]'::jsonb, 3, 5, true, v_p);
  insert into public.english_test_passages (passage_text) values ('This morning we received a complaint from the client about the quarterly report we delivered on Monday. According to their message, the section covering vendor expenses was left out of the file, even though it appears in the table of contents. After reviewing our records, we confirmed the section was written but was removed by mistake when the document was exported. Our team is adding it back now, and a corrected copy should be ready by tomorrow afternoon. Once I have approved that version, please resend it to the client with a brief apology and confirm that they received the complete file.') returning id into v_p;
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What is this message mainly about?', '["A delay in paying a vendor''s invoice", "An error in a recently delivered report", "A client''s request to cancel their contract", "A change to the team''s weekly schedule"]'::jsonb, 1, 1, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'According to the message, when should the corrected copy be ready?', '["By Monday morning", "Later this morning", "By tomorrow afternoon", "By the end of next week"]'::jsonb, 2, 2, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'Why was the section missing from the file?', '["The client asked for it to be deleted", "The team never finished writing it", "It was saved in a separate document", "It was accidentally removed during export"]'::jsonb, 3, 3, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'What will most likely happen after the writer approves the corrected version?', '["The client will be sent the corrected report", "The team will begin writing the missing section", "The writer will call the client to apologize", "The vendor will be asked to explain the expenses"]'::jsonb, 0, 4, true, v_p);
  insert into public.english_test_questions (section, question_text, options, correct_answer, display_order, active, passage_id) values ('comprehension', 'In this message, what does the phrase "left out" mean?', '["Sent too late", "Printed twice", "Not included", "Poorly written"]'::jsonb, 2, 5, true, v_p);
end $$;
